const fs = require('fs');
const path = require('path');

/**
 * Scans a project directory for .env.example or .env.template
 * Parses the keys and returns them.
 */
function scanForEnvKeys(projectPath) {
    const possibleFiles = ['.env.example', '.env.template', '.env.sample'];
    let keys = [];
    
    for (const file of possibleFiles) {
        const fullPath = path.join(projectPath, file);
        if (fs.existsSync(fullPath)) {
            const content = fs.readFileSync(fullPath, 'utf8');
            const lines = content.split('\n');
            
            for (const line of lines) {
                const trimmed = line.trim();
                if (trimmed && !trimmed.startsWith('#')) {
                    // Match KEY=value or just KEY
                    const match = trimmed.match(/^([^=]+)=?(.*)$/);
                    if (match && match[1]) {
                        keys.push({
                            key: match[1].trim(),
                            defaultValue: match[2] ? match[2].trim().replace(/^['"]|['"]$/g, '') : ''
                        });
                    }
                }
            }
            break; // Stop at first found file
        }
    }
    
    return keys;
}

/**
 * Writes the provided env variables to both .env and .env.local in the project directory
 * .env.local is for Next.js / Vite apps
 * .env is for generic Node.js apps
 */
function writeEnvFile(projectPath, envVars) {
    if (!envVars || Object.keys(envVars).length === 0) return;
    
    let content = '# Auto-generated by Server Hosting Platform\n';
    
    for (const [key, value] of Object.entries(envVars)) {
        // Wrap values with spaces or special chars in quotes
        const needsQuotes = /[\s#"'`]/.test(value);
        const formatted = needsQuotes ? `"${value.replace(/"/g, '\\"')}"` : value;
        content += `${key}=${formatted}\n`;
    }
    
    // Write to .env (generic Node.js)
    fs.writeFileSync(path.join(projectPath, '.env'), content);
    // Write to .env.local (Next.js / Vite - takes priority)
    fs.writeFileSync(path.join(projectPath, '.env.local'), content);
    
    console.log(`Wrote ${Object.keys(envVars).length} environment variable(s) to .env and .env.local`);
}

module.exports = {
    scanForEnvKeys,
    writeEnvFile
};
